fn build_assurance_catalog(
    workspace_root: &Utf8PathBuf,
    options: &AssuranceOptions,
    benchmark_report: &Utf8PathBuf,
    rust_compare_report: &Utf8PathBuf,
    rust_compare_raw_report: &Utf8PathBuf,
    browser_compare_report: &Utf8PathBuf,
    browser_compare_smoke_report: &Utf8PathBuf,
) -> Vec<AssuranceCheckSpec> {
    let rust_goldens_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("rust-goldens-comparison.json"),
    );
    let node_goldens_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("node-goldens-comparison.json"),
    );
    let browser_goldens_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("browser-goldens-comparison.json"),
    );
    let react_native_goldens_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("react-native-goldens-comparison.json"),
    );
    let node_stateful_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("node-stateful-comparison.json"),
    );
    let react_native_stateful_report = resolve_path_for_child(
        workspace_root,
        &options
            .out_dir
            .join("react-native-stateful-comparison.json"),
    );
    let rust_compare_report_for_child = resolve_path_for_child(workspace_root, rust_compare_report);
    let rust_compare_raw_report_for_child =
        resolve_path_for_child(workspace_root, rust_compare_raw_report);
    let browser_compare_report_for_child =
        resolve_path_for_child(workspace_root, browser_compare_report);
    let browser_compare_smoke_report_for_child =
        resolve_path_for_child(workspace_root, browser_compare_smoke_report);
    let sdk_sbom_report =
        resolve_path_for_child(workspace_root, &options.out_dir.join("sbom/sdk.spdx.json"));
    let react_native_sbom_report = resolve_path_for_child(
        workspace_root,
        &options.out_dir.join("sbom/react-native.spdx.json"),
    );
    let node_fail_closed_pattern = [
        "Circuits rejects unsigned manifests unless the test-only override is enabled",
        "Circuits rejects signed manifests with the wrong public key",
        "Circuits rejects tampered signed-manifest artifact bytes",
        "node addon rejects malformed proof bundle shapes",
        "node addon enforces secret and verified proof handle kinds",
        "node addon rejects invalid execution preflight policies and signer mismatches",
        "node addon proves and verifies withdrawal proofs",
        "node addon fails closed for invalid proving artifacts and stale sessions",
    ]
    .join("|");
    let mut checks = vec![
        assurance_check_spec(
            "rust-fmt",
            "cargo fmt --all --check",
            vec![AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "fmt".to_owned(),
                "--all".to_owned(),
                "--check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-fmt.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-clippy",
            "cargo clippy --workspace --all-targets --all-features --locked -- -D warnings",
            vec![AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "clippy".to_owned(),
                "--workspace".to_owned(),
                "--all-targets".to_owned(),
                "--all-features".to_owned(),
                "--locked".to_owned(),
                "--".to_owned(),
                "-D".to_owned(),
                "warnings".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-clippy.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "cargo-test-workspace",
            "cargo nextest run --workspace --locked --profile ci",
            vec![AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "nextest".to_owned(),
                "run".to_owned(),
                "--workspace".to_owned(),
                "--locked".to_owned(),
                "--profile".to_owned(),
                "ci".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "cargo-test-workspace.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-malformed-input-check",
            "cargo test -p privacy-pools-sdk-core --locked malformed_",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "-p".to_owned(),
                "privacy-pools-sdk-core".to_owned(),
                "--locked".to_owned(),
                "malformed_".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-malformed-input-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-secret-hardening-check",
            "cargo test -p privacy-pools-sdk-core --locked secret_domain_traits_do_not_compile",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "-p".to_owned(),
                "privacy-pools-sdk-core".to_owned(),
                "--locked".to_owned(),
                "secret_domain_traits_do_not_compile".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-secret-hardening-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-verified-proof-safety-check",
            "cargo test -p privacy-pools-sdk --locked verified_proof_planners_reject_raw_proof_bundles",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "-p".to_owned(),
                "privacy-pools-sdk".to_owned(),
                "--locked".to_owned(),
                "verified_proof_planners_reject_raw_proof_bundles".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-verified-proof-safety-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-chain-rejection-checks",
            "cargo test -p privacy-pools-sdk-chain --locked rejects_",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "-p".to_owned(),
                "privacy-pools-sdk-chain".to_owned(),
                "--locked".to_owned(),
                "rejects_".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-chain-rejection-checks.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "rust-signer-local-tests",
            "cargo test -p privacy-pools-sdk-signer --locked --features local-mnemonic",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "-p".to_owned(),
                "privacy-pools-sdk-signer".to_owned(),
                "--locked".to_owned(),
                "--features".to_owned(),
                "local-mnemonic".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "rust-signer-local-tests.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "cargo-test-doc-workspace",
            "cargo test --doc --workspace --locked",
            vec![AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "test".to_owned(),
                "--doc".to_owned(),
                "--workspace".to_owned(),
                "--locked".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "cargo-test-doc-workspace.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "examples-check",
            "cargo run -p xtask -- examples-check",
            vec![AssuranceRuntime::Rust, AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "examples-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "examples-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "feature-check",
            "cargo run -p xtask -- feature-check",
            vec![AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "feature-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "feature-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "package-check",
            "cargo run -p xtask -- package-check",
            vec![AssuranceRuntime::Shared],
            "packaging",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "package-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "package-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "dependency-check",
            "cargo run -p xtask -- dependency-check",
            vec![AssuranceRuntime::Shared],
            "supply-chain",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "dependency-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "dependency-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "docs-check",
            "cargo run -p xtask -- docs-check",
            vec![AssuranceRuntime::Shared],
            "documentation",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "docs-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "docs-check.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "artifact-fingerprints",
            "cargo run -p xtask -- artifact-fingerprints --check",
            vec![AssuranceRuntime::Shared],
            "supply-chain",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "artifact-fingerprints".to_owned(),
                "--check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "artifact-fingerprints.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "signed-manifest-sample-check",
            "cargo run -p xtask -- signed-manifest-sample-check",
            vec![AssuranceRuntime::Shared],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "signed-manifest-sample-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "signed-manifest-sample-check.log",
            vec![],
            None,
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "cargo-deny-policy",
                "cargo deny --locked check bans licenses sources",
                vec![AssuranceRuntime::Shared],
                "supply-chain",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "deny".to_owned(),
                    "--locked".to_owned(),
                    "check".to_owned(),
                    "bans".to_owned(),
                    "licenses".to_owned(),
                    "sources".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "cargo-deny-policy.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "cargo-deny-advisories",
                "cargo deny --locked check advisories",
                vec![AssuranceRuntime::Shared],
                "supply-chain",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "deny".to_owned(),
                    "--locked".to_owned(),
                    "check".to_owned(),
                    "advisories".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "cargo-deny-advisories.log",
                vec![],
                None,
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "cargo-vet",
                "cargo vet --locked",
                vec![AssuranceRuntime::Shared],
                "supply-chain",
                AssuranceCheckMode::Normative,
                "cargo",
                vec!["vet".to_owned(), "--locked".to_owned()],
                workspace_root.clone(),
                vec![],
                "cargo-vet.log",
                vec![],
                None,
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "zizmor",
                "zizmor .github/workflows",
                vec![AssuranceRuntime::Shared],
                "supply-chain",
                AssuranceCheckMode::Normative,
                "zizmor",
                vec![".github/workflows".to_owned()],
                workspace_root.clone(),
                vec![],
                "zizmor.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "madge-cycles",
                "npx madge --circular --extensions ts,tsx,mjs,js,cjs packages/",
                vec![AssuranceRuntime::Shared],
                "correctness",
                AssuranceCheckMode::Normative,
                "npx",
                vec![
                    "madge".to_owned(),
                    "--circular".to_owned(),
                    "--extensions".to_owned(),
                    "ts,tsx,mjs,js,cjs".to_owned(),
                    "packages/".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "madge-cycles.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "action-pins",
                "cargo run -p xtask -- action-pins",
                vec![AssuranceRuntime::Shared],
                "supply-chain",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "run".to_owned(),
                    "-p".to_owned(),
                    "xtask".to_owned(),
                    "--".to_owned(),
                    "action-pins".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "action-pins.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "rust-internal-cycles",
                "cargo run -p xtask -- check-internal-cycles",
                vec![AssuranceRuntime::Shared],
                "correctness",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "run".to_owned(),
                    "-p".to_owned(),
                    "xtask".to_owned(),
                    "--".to_owned(),
                    "check-internal-cycles".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "rust-internal-cycles.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "check-binding-parity",
                "cargo run -p xtask -- check-binding-parity",
                vec![AssuranceRuntime::Shared],
                "correctness",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "run".to_owned(),
                    "-p".to_owned(),
                    "xtask".to_owned(),
                    "--".to_owned(),
                    "check-binding-parity".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "check-binding-parity.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "ffi-input-bound-lint",
                "cargo run -p xtask -- ffi-input-bound-lint",
                vec![AssuranceRuntime::Shared],
                "funds-safety",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "run".to_owned(),
                    "-p".to_owned(),
                    "xtask".to_owned(),
                    "--".to_owned(),
                    "ffi-input-bound-lint".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "ffi-input-bound-lint.log",
                vec![],
                None,
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_spec(
            "bindings-generate",
            "cargo run -p xtask -- bindings",
            vec![AssuranceRuntime::ReactNative, AssuranceRuntime::Shared],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "bindings".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "bindings-generate.log",
            vec![],
            None,
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "bindings-drift-check",
                "git diff --exit-code -- bindings/ios/generated bindings/android/generated",
                vec![AssuranceRuntime::ReactNative, AssuranceRuntime::Shared],
                "correctness",
                AssuranceCheckMode::Normative,
                "git",
                vec![
                    "diff".to_owned(),
                    "--exit-code".to_owned(),
                    "--".to_owned(),
                    "bindings/ios/generated".to_owned(),
                    "bindings/android/generated".to_owned(),
                ],
                workspace_root.clone(),
                vec![],
                "bindings-drift-check.log",
                vec![],
                None,
            ),
            vec!["bindings-generate".to_owned()],
        ),
        assurance_check_spec(
            "sdk-native-build",
            "npm run build:native",
            vec![AssuranceRuntime::Node, AssuranceRuntime::ReactNative],
            "correctness",
            AssuranceCheckMode::Normative,
            "npm",
            vec!["run".to_owned(), "build:native".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![],
            "sdk-native-build.log",
            vec![],
            None,
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "sdk-node-smoke",
                "npm run test:node",
                vec![AssuranceRuntime::Node],
                "correctness",
                AssuranceCheckMode::Normative,
                "npm",
                vec!["run".to_owned(), "test:node".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![],
                "sdk-node-smoke.log",
                vec![],
                None,
            ),
            vec!["sdk-native-build".to_owned()],
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "sdk-node-fail-closed-checks",
                "node --test ./test/facade.test.mjs ./test/node.test.mjs --test-name-pattern <node fail-closed>",
                vec![AssuranceRuntime::Node],
                "funds-safety",
                AssuranceCheckMode::Normative,
                "node",
                vec![
                    "--test".to_owned(),
                    "--test-name-pattern".to_owned(),
                    node_fail_closed_pattern,
                    "./test/facade.test.mjs".to_owned(),
                    "./test/node.test.mjs".to_owned(),
                ],
                workspace_root.join("packages/sdk"),
                vec![],
                "sdk-node-fail-closed-checks.log",
                vec![],
                None,
            ),
            vec!["sdk-native-build".to_owned()],
        ),
        assurance_check_spec(
            "sdk-browser-build",
            "cargo run -p xtask -- sdk-web-package --debug",
            vec![AssuranceRuntime::Browser],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "sdk-web-package".to_owned(),
                "--debug".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "sdk-browser-build.log",
            vec![],
            None,
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "sdk-browser-smoke",
                "npm run test:browser:smoke",
                vec![AssuranceRuntime::Browser],
                "correctness",
                AssuranceCheckMode::Normative,
                "npm",
                vec!["run".to_owned(), "test:browser:smoke".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![],
                "sdk-browser-smoke.log",
                vec![],
                None,
            ),
            vec!["sdk-browser-build".to_owned()],
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "sdk-browser-generated-drift-check",
                "node ./scripts/check-generated.mjs --mode pr-safe",
                vec![AssuranceRuntime::Browser],
                "correctness",
                AssuranceCheckMode::Normative,
                "node",
                vec![
                    "./scripts/check-generated.mjs".to_owned(),
                    "--mode".to_owned(),
                    "pr-safe".to_owned(),
                ],
                workspace_root.join("packages/sdk"),
                vec![],
                "sdk-browser-generated-drift-check.log",
                vec![],
                None,
            ),
            vec!["sdk-browser-build".to_owned()],
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "sdk-browser-fail-closed-checks",
                "npm run test:browser:pr-fail-closed",
                vec![AssuranceRuntime::Browser],
                "funds-safety",
                AssuranceCheckMode::Normative,
                "npm",
                vec!["run".to_owned(), "test:browser:pr-fail-closed".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![],
                "sdk-browser-fail-closed-checks.log",
                vec![],
                None,
            ),
            vec!["sdk-browser-build".to_owned()],
        ),
        assurance_check_with_profiles(
            assurance_check_with_dependencies(
                assurance_check_spec(
                    "sdk-browser-core",
                    "npm run test:browser:core",
                    vec![AssuranceRuntime::Browser],
                    "correctness",
                    AssuranceCheckMode::Normative,
                    "npm",
                    vec!["run".to_owned(), "test:browser:core".to_owned()],
                    workspace_root.join("packages/sdk"),
                    vec![],
                    "sdk-browser-core.log",
                    vec![],
                    None,
                ),
                vec!["sdk-browser-build".to_owned()],
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_with_dependencies(
                assurance_check_spec(
                    "sdk-browser-direct-execution",
                    "npm run test:browser:direct",
                    vec![AssuranceRuntime::Browser],
                    "correctness",
                    AssuranceCheckMode::Normative,
                    "npm",
                    vec!["run".to_owned(), "test:browser:direct".to_owned()],
                    workspace_root.join("packages/sdk"),
                    vec![],
                    "sdk-browser-direct-execution.log",
                    vec![],
                    None,
                ),
                vec!["sdk-browser-build".to_owned()],
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_with_dependencies(
                assurance_check_spec(
                    "sdk-browser-worker-suite",
                    "npm run test:browser:worker",
                    vec![AssuranceRuntime::Browser],
                    "correctness",
                    AssuranceCheckMode::Normative,
                    "npm",
                    vec!["run".to_owned(), "test:browser:worker".to_owned()],
                    workspace_root.join("packages/sdk"),
                    vec![],
                    "sdk-browser-worker-suite.log",
                    vec![],
                    None,
                ),
                vec!["sdk-browser-build".to_owned()],
            ),
            vec![
                AssuranceProfile::Pr,
                AssuranceProfile::Nightly,
                AssuranceProfile::Release,
            ],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "browser-threaded-build",
                "npm run build:web:experimental-threaded",
                vec![AssuranceRuntime::Browser],
                "correctness",
                AssuranceCheckMode::Normative,
                "npm",
                vec![
                    "run".to_owned(),
                    "build:web:experimental-threaded".to_owned(),
                ],
                workspace_root.join("packages/sdk"),
                vec![],
                "browser-threaded-build.log",
                vec![],
                None,
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_with_dependencies(
                assurance_check_spec(
                    "browser-threaded-drift-check",
                    "git diff --exit-code -- packages/sdk/src/browser/generated-threaded",
                    vec![AssuranceRuntime::Browser],
                    "correctness",
                    AssuranceCheckMode::Normative,
                    "git",
                    vec![
                        "diff".to_owned(),
                        "--exit-code".to_owned(),
                        "--".to_owned(),
                        "packages/sdk/src/browser/generated-threaded".to_owned(),
                    ],
                    workspace_root.clone(),
                    vec![],
                    "browser-threaded-drift-check.log",
                    vec![],
                    None,
                ),
                vec!["browser-threaded-build".to_owned()],
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_spec(
            "sdk-package-dry-run",
            "npm pack --dry-run --json",
            vec![AssuranceRuntime::Node, AssuranceRuntime::Browser],
            "packaging",
            AssuranceCheckMode::Normative,
            "npm",
            vec![
                "pack".to_owned(),
                "--dry-run".to_owned(),
                "--json".to_owned(),
            ],
            workspace_root.join("packages/sdk"),
            vec![],
            "sdk-package-dry-run.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "react-native-package",
            "cargo run -p xtask -- react-native-package",
            vec![AssuranceRuntime::ReactNative],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "react-native-package".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "react-native-package.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "react-native-smoke",
            "cargo run -p xtask -- react-native-smoke",
            vec![AssuranceRuntime::ReactNative],
            "correctness",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "react-native-smoke".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "react-native-smoke.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "react-native-package-dry-run",
            "npm pack --dry-run --json",
            vec![AssuranceRuntime::ReactNative],
            "packaging",
            AssuranceCheckMode::Normative,
            "npm",
            vec![
                "pack".to_owned(),
                "--dry-run".to_owned(),
                "--json".to_owned(),
            ],
            workspace_root.join("packages/react-native"),
            vec![],
            "react-native-package-dry-run.log",
            vec![],
            None,
        ),
        assurance_check_spec(
            "compare-rust-goldens-rust",
            "node ./scripts/compare-rust-goldens.mjs",
            vec![AssuranceRuntime::Rust],
            "correctness",
            AssuranceCheckMode::Normative,
            "node",
            vec!["./scripts/compare-rust-goldens.mjs".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![
                (
                    "PRIVACY_POOLS_GOLDENS_RUNTIME".to_owned(),
                    "rust".to_owned(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_REPORT".to_owned(),
                    rust_goldens_report.to_string(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_SMOKE".to_owned(),
                    if matches!(options.profile, AssuranceProfile::Pr) {
                        "1".to_owned()
                    } else {
                        "0".to_owned()
                    },
                ),
            ],
            "compare-rust-goldens-rust.log",
            vec![options.out_dir.join("rust-goldens-comparison.json")],
            None,
        ),
        assurance_check_spec(
            "compare-rust-goldens-node",
            "node ./scripts/compare-rust-goldens.mjs",
            vec![AssuranceRuntime::Node],
            "correctness",
            AssuranceCheckMode::Normative,
            "node",
            vec!["./scripts/compare-rust-goldens.mjs".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![
                (
                    "PRIVACY_POOLS_GOLDENS_RUNTIME".to_owned(),
                    "node".to_owned(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_REPORT".to_owned(),
                    node_goldens_report.to_string(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_SMOKE".to_owned(),
                    if matches!(options.profile, AssuranceProfile::Pr) {
                        "1".to_owned()
                    } else {
                        "0".to_owned()
                    },
                ),
            ],
            "compare-rust-goldens-node.log",
            vec![options.out_dir.join("node-goldens-comparison.json")],
            None,
        ),
        assurance_check_with_dependencies(
            assurance_check_spec(
                "compare-rust-goldens-browser",
                "node ./scripts/compare-rust-goldens.mjs",
                vec![AssuranceRuntime::Browser],
                "correctness",
                AssuranceCheckMode::Normative,
                "node",
                vec!["./scripts/compare-rust-goldens.mjs".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![
                    (
                        "PRIVACY_POOLS_GOLDENS_RUNTIME".to_owned(),
                        "browser".to_owned(),
                    ),
                    (
                        "PRIVACY_POOLS_GOLDENS_REPORT".to_owned(),
                        browser_goldens_report.to_string(),
                    ),
                    (
                        "PRIVACY_POOLS_GOLDENS_SMOKE".to_owned(),
                        if matches!(options.profile, AssuranceProfile::Pr) {
                            "1".to_owned()
                        } else {
                            "0".to_owned()
                        },
                    ),
                ],
                "compare-rust-goldens-browser.log",
                vec![options.out_dir.join("browser-goldens-comparison.json")],
                None,
            ),
            vec!["sdk-browser-build".to_owned()],
        ),
        assurance_check_spec(
            "compare-rust-goldens-react-native",
            "node ./scripts/compare-rust-goldens.mjs",
            vec![AssuranceRuntime::ReactNative],
            "correctness",
            AssuranceCheckMode::Normative,
            "node",
            vec!["./scripts/compare-rust-goldens.mjs".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![
                (
                    "PRIVACY_POOLS_GOLDENS_RUNTIME".to_owned(),
                    "react-native".to_owned(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_REPORT".to_owned(),
                    react_native_goldens_report.to_string(),
                ),
                (
                    "PRIVACY_POOLS_GOLDENS_SMOKE".to_owned(),
                    if matches!(options.profile, AssuranceProfile::Pr) {
                        "1".to_owned()
                    } else {
                        "0".to_owned()
                    },
                ),
            ],
            "compare-rust-goldens-react-native.log",
            vec![options.out_dir.join("react-native-goldens-comparison.json")],
            None,
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "compare-rust-stateful-node",
                "node ./scripts/compare-rust-stateful.mjs",
                vec![AssuranceRuntime::Node],
                "correctness",
                AssuranceCheckMode::Normative,
                "node",
                vec!["./scripts/compare-rust-stateful.mjs".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![
                    (
                        "PRIVACY_POOLS_STATEFUL_RUNTIME".to_owned(),
                        "node".to_owned(),
                    ),
                    (
                        "PRIVACY_POOLS_STATEFUL_REPORT".to_owned(),
                        node_stateful_report.to_string(),
                    ),
                ],
                "compare-rust-stateful-node.log",
                vec![options.out_dir.join("node-stateful-comparison.json")],
                None,
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "compare-rust-stateful-react-native",
                "node ./scripts/compare-rust-stateful.mjs",
                vec![AssuranceRuntime::ReactNative],
                "correctness",
                AssuranceCheckMode::Normative,
                "node",
                vec!["./scripts/compare-rust-stateful.mjs".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![
                    (
                        "PRIVACY_POOLS_STATEFUL_RUNTIME".to_owned(),
                        "react-native".to_owned(),
                    ),
                    (
                        "PRIVACY_POOLS_STATEFUL_REPORT".to_owned(),
                        react_native_stateful_report.to_string(),
                    ),
                ],
                "compare-rust-stateful-react-native.log",
                vec![
                    options
                        .out_dir
                        .join("react-native-stateful-comparison.json"),
                ],
                None,
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
        assurance_check_with_profiles(
            assurance_check_spec(
                "compare-v1-rust",
                "npm run compare:v1-rust",
                vec![AssuranceRuntime::Rust],
                "funds-safety",
                AssuranceCheckMode::Normative,
                "npm",
                vec!["run".to_owned(), "compare:v1-rust".to_owned()],
                workspace_root.join("packages/sdk"),
                vec![
                    (
                        "PRIVACY_POOLS_COMPARE_RUST_REPORT".to_owned(),
                        rust_compare_report_for_child.to_string(),
                    ),
                    (
                        "PRIVACY_POOLS_COMPARE_RUST_CLI_REPORT".to_owned(),
                        rust_compare_raw_report_for_child.to_string(),
                    ),
                    (
                        "PRIVACY_POOLS_V1_BASELINE_PATH".to_owned(),
                        options.v1_package_path.to_string(),
                    ),
                    (
                        "PRIVACY_POOLS_V1_SOURCE_PATH".to_owned(),
                        options.v1_source_path.to_string(),
                    ),
                ],
                "compare-v1-rust.log",
                vec![rust_compare_report.clone(), rust_compare_raw_report.clone()],
                Some(json!({ "helperMaxRatio": 1.05, "proofMaxRatio": 1.15 })),
            ),
            vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
        ),
    ];

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "compare-v1-npm-smoke",
            "npm run compare:v1-npm (smoke)",
            vec![AssuranceRuntime::Browser],
            "correctness",
            AssuranceCheckMode::Informational,
            "npm",
            vec!["run".to_owned(), "compare:v1-npm".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![
                (
                    "PRIVACY_POOLS_COMPARE_REPORT".to_owned(),
                    browser_compare_smoke_report_for_child.to_string(),
                ),
                (
                    "PRIVACY_POOLS_V1_BASELINE_PATH".to_owned(),
                    options.v1_package_path.to_string(),
                ),
                (
                    "PRIVACY_POOLS_COMPARE_HELPER_ITERS".to_owned(),
                    "1".to_owned(),
                ),
                (
                    "PRIVACY_POOLS_COMPARE_PROOF_ITERS".to_owned(),
                    "1".to_owned(),
                ),
            ],
            "compare-v1-npm-smoke.log",
            vec![browser_compare_smoke_report.clone()],
            None,
        ),
        vec![AssuranceProfile::Nightly],
    ));

    let fuzz_targets = [
        "field_parsing",
        "wire_conversion",
        "proof_bundle_parsing",
        "manifest_parsing",
        "json_boundaries",
        "artifact_bundle_resolution",
        "session_invalidation",
        "execution_policy_inputs",
        "groth16_verifier_fuzz",
        "relay_data_abi_fuzz",
        "merkle_proof_tamper_fuzz",
    ];
    for target in fuzz_targets {
        let runs_arg = format!("-runs={}", options.fuzz_runs);
        checks.push(assurance_check_with_profiles(
            assurance_check_spec(
                format!("fuzz-{target}"),
                format!("cargo fuzz run {target} --target x86_64-unknown-linux-gnu -- {runs_arg}"),
                vec![AssuranceRuntime::Rust],
                "funds-safety",
                AssuranceCheckMode::Normative,
                "cargo",
                vec![
                    "fuzz".to_owned(),
                    "run".to_owned(),
                    target.to_owned(),
                    "--target".to_owned(),
                    "x86_64-unknown-linux-gnu".to_owned(),
                    "--".to_owned(),
                    runs_arg,
                ],
                workspace_root.join("fuzz"),
                vec![],
                format!("fuzz-{target}.log"),
                vec![],
                None,
            ),
            vec![AssuranceProfile::Nightly],
        ));
    }

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "compare-v1-npm",
            "npm run compare:v1-npm",
            vec![AssuranceRuntime::Browser],
            "correctness",
            AssuranceCheckMode::Informational,
            "npm",
            vec!["run".to_owned(), "compare:v1-npm".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![
                (
                    "PRIVACY_POOLS_COMPARE_REPORT".to_owned(),
                    browser_compare_report_for_child.to_string(),
                ),
                (
                    "PRIVACY_POOLS_V1_BASELINE_PATH".to_owned(),
                    options.v1_package_path.to_string(),
                ),
            ],
            "compare-v1-npm.log",
            vec![browser_compare_report.clone()],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "sdk-native-build-release",
            "npm run build:native:release",
            vec![AssuranceRuntime::Node, AssuranceRuntime::ReactNative],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "npm",
            vec!["run".to_owned(), "build:native:release".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![],
            "sdk-native-build-release.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "release-debug-node-react-native",
            "node ./scripts/check-release-debug-node-react-native.mjs",
            vec![AssuranceRuntime::Node, AssuranceRuntime::ReactNative],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "node",
            vec!["./scripts/check-release-debug-node-react-native.mjs".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![],
            "release-debug-node-react-native.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "sdk-web-release-build",
            "npm run build:web:release",
            vec![AssuranceRuntime::Browser],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "npm",
            vec!["run".to_owned(), "build:web:release".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![],
            "sdk-web-release-build.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "release-debug-browser",
            "node ./scripts/check-release-debug-browser.mjs",
            vec![AssuranceRuntime::Browser],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "node",
            vec!["./scripts/check-release-debug-browser.mjs".to_owned()],
            workspace_root.join("packages/sdk"),
            vec![],
            "release-debug-browser.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "geiger-delta-check",
            "cargo run -p xtask -- geiger-delta-check",
            vec![AssuranceRuntime::Shared],
            "supply-chain",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "run".to_owned(),
                "-p".to_owned(),
                "xtask".to_owned(),
                "--".to_owned(),
                "geiger-delta-check".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "geiger-delta-check.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    checks.push(assurance_check_with_profiles(
        assurance_check_spec(
            "cargo-mutants-high-risk",
            "cargo mutants --in-place --baseline skip",
            vec![AssuranceRuntime::Rust],
            "funds-safety",
            AssuranceCheckMode::Normative,
            "cargo",
            vec![
                "mutants".to_owned(),
                "--in-place".to_owned(),
                "--baseline".to_owned(),
                "skip".to_owned(),
                "--timeout".to_owned(),
                "1200".to_owned(),
                "--minimum-test-timeout".to_owned(),
                "60".to_owned(),
                "--jobs".to_owned(),
                "2".to_owned(),
                "--package".to_owned(),
                "privacy-pools-sdk-artifacts".to_owned(),
                "--package".to_owned(),
                "privacy-pools-sdk-verifier".to_owned(),
                "--package".to_owned(),
                "privacy-pools-sdk-chain".to_owned(),
            ],
            workspace_root.clone(),
            vec![],
            "cargo-mutants-high-risk.log",
            vec![],
            None,
        ),
        vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
    ));

    if let Some(external_evidence_dir) = options.external_evidence_dir.as_ref() {
        let mobile_evidence_dir = resolve_path_for_child(workspace_root, external_evidence_dir);
        if mobile_evidence_files_present(&mobile_evidence_dir) {
            checks.push(assurance_check_with_profiles(
                assurance_check_with_dependencies(
                    assurance_check_spec(
                        "mobile-evidence-check",
                        "cargo run -p xtask -- mobile-evidence-check",
                        vec![AssuranceRuntime::ReactNative],
                        "correctness",
                        AssuranceCheckMode::Normative,
                        "cargo",
                        vec![
                            "run".to_owned(),
                            "-p".to_owned(),
                            "xtask".to_owned(),
                            "--".to_owned(),
                            "mobile-evidence-check".to_owned(),
                            "--dir".to_owned(),
                            mobile_evidence_dir.to_string(),
                        ],
                        workspace_root.clone(),
                        vec![],
                        "mobile-evidence-check.log",
                        vec![],
                        None,
                    ),
                    vec!["external-evidence-validation".to_owned()],
                ),
                vec![AssuranceProfile::Nightly, AssuranceProfile::Release],
            ));
        }
    }

    append_release_acceptance_check(&mut checks, workspace_root, options);
    append_informational_sbom_and_benchmark_checks(
        &mut checks,
        workspace_root,
        options,
        benchmark_report,
        &sdk_sbom_report,
        &react_native_sbom_report,
    );

    checks
        .into_iter()
        .map(finalize_assurance_check_spec)
        .collect()
}
